# Generated by Django 4.2.1 on 2023-05-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_producto_disponibilidad_alter_menu_restaurante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='disponibilidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
