# Generated by Django 4.2.1 on 2023-06-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_pagable',
            field=models.BooleanField(default=False),
        ),
    ]
