# Generated by Django 4.2.1 on 2023-05-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.ingrediente')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='ingrediente',
            field=models.ManyToManyField(blank=True, through='cliente.MenuIngrediente', to='cliente.ingrediente'),
        ),
    ]
