# Generated by Django 4.2.1 on 2023-05-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_client_password_alter_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuproducto',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='restaurante',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='sede',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuProducto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
