# Generated by Django 4.2.1 on 2023-05-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_remove_menu_ingrediente_remove_menu_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='imagen',
        ),
        migrations.AddField(
            model_name='menu',
            name='ingrediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.ingrediente'),
        ),
        migrations.AddField(
            model_name='menu',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.producto'),
        ),
    ]
