# Generated by Django 4.2.1 on 2023-05-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_remove_menu_imagen_menu_ingrediente_menu_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ingrediente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.ingrediente'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='producto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.producto'),
        ),
    ]
